version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/assets
    depends_on:
      - db
    volumes:
      - ./:/app
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4 --reload"

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=assets
    ports:
      - "5432:5432"

volumes:
  postgres_data:
