name: Django App CI/CD

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'
  
      - name: Build Docker image
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} > aws_access_key
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} > aws_secret_key
          aws configure set aws_access_key_id "$(cat aws_access_key)"
          aws configure set aws_secret_access_key "$(cat aws_secret_key)"
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 024881612673.dkr.ecr.eu-west-1.amazonaws.com
          cd django_asset_project
          docker build  . \
            -t 024881612673.dkr.ecr.eu-west-1.amazonaws.com/one-million-request:latest

      - name: Push Docker image to ECR
        run: |
          docker push 024881612673.dkr.ecr.eu-west-1.amazonaws.com/one-million-request:latest
